name: Deploy functions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  format-checking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run flake8 (with adjustments to allow for black's formatting)
      run: flake8 *.py --extend-ignore E203  --extend-ignore E722 --max-line-length 120
   
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run mypy
        run: |
          mypy *.py
        
  testing:
    runs-on: ubuntu-latest
    needs: [format-checking, type-checking]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Set environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unit tests using pytest with coverage
      run: | 
        pytest --cov=. 

  deploy-functions:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Confirm Google Cloud Authentication
        run: gcloud auth list

      - name: Deploy api_create_event
        run: |
          gcloud functions deploy api_create_event \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_create_event \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_event_info
        run: |
          gcloud functions deploy api_get_event_info \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_event_info \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_delete_event
        run: |
          gcloud functions deploy api_delete_event \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_delete_event \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_event_info
        run: |
          gcloud functions deploy api_get_event_info \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_event_info \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_events_for_venue
        run: |
          gcloud functions deploy api_get_events_for_venue \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_events_for_venue \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_events_for_artist
        run: |
          gcloud functions deploy api_get_events_for_artist \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_events_for_artist \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_events_for_attendee
        run: |
          gcloud functions deploy api_get_events_for_attendee \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_events_for_attendee \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_events_in_city
        run: |
          gcloud functions deploy api_get_events_in_city \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_events_in_city \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_cities_by_country
        run: |
          gcloud functions deploy api_get_cities_by_country \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_cities_by_country \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_apply_for_gig
        run: |
          gcloud functions deploy api_apply_for_gig \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_apply_for_gig \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_update_event
        run: |
          gcloud functions deploy api_update_event \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_update_event \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest